import { NavigationMenu } from "./navigationTypes";

export const navigationData: NavigationMenu = {
  cou1: {
    id: "cou1",
    heading: "Course Heading",
    path: "/course/cou1",
    type: "course",
    childrenIds: [
      "chapter 1 heading-/course/cou1/chapter/cha1",
      "chapter 2 heading-/course/cou1/chapter/cha2",
    ],
  },
  "chapter 1 heading-/course/cou1/chapter/cha1": {
    id: "chapter 1 heading-/course/cou1/chapter/cha1",
    heading: "chapter 1 heading",
    path: "/course/cou1/chapter/cha1",
    type: "chapter",
    index: "1",
    childrenIds: ["Group section 1-no-path", "Group section 2-no-path"],
    parentId: "cou1",
  },
  "Group section 1-no-path": {
    id: "Group section 1-no-path",
    heading: "Group section 1",
    path: "",
    type: "section-group",
    childrenIds: ["page 1-/course/cou1/page/pag1"],
    parentId: "chapter 1 heading-/course/cou1/chapter/cha1",
  },
  "page 1-/course/cou1/page/pag1": {
    id: "page 1-/course/cou1/page/pag1",
    heading: "page 1",
    path: "/course/cou1/page/pag1",
    type: "page",
    childrenIds: [
      "panel 1 heading-/course/cou1/page/pag1",
      "panel 2 heading-/course/cou1/page/pag1/panel/pan2",
      "panel 3 heading-/course/cou1/page/pag1/panel/pan3",
    ],
    parentId: "Group section 1-no-path",
  },
  "panel 1 heading-/course/cou1/page/pag1": {
    id: "panel 1 heading-/course/cou1/page/pag1",
    heading: "panel 1 heading",
    path: "/course/cou1/page/pag1",
    type: "page-panel",
    childrenIds: [],
    parentId: "page 1-/course/cou1/page/pag1",
  },
  "panel 2 heading-/course/cou1/page/pag1/panel/pan2": {
    id: "panel 2 heading-/course/cou1/page/pag1/panel/pan2",
    heading: "panel 2 heading",
    path: "/course/cou1/page/pag1/panel/pan2",
    type: "page-panel",
    childrenIds: [],
    parentId: "page 1-/course/cou1/page/pag1",
  },
  "panel 3 heading-/course/cou1/page/pag1/panel/pan3": {
    id: "panel 3 heading-/course/cou1/page/pag1/panel/pan3",
    heading: "panel 3 heading",
    path: "/course/cou1/page/pag1/panel/pan3",
    type: "page-panel",
    childrenIds: [],
    parentId: "page 1-/course/cou1/page/pag1",
  },
  "Group section 2-no-path": {
    id: "Group section 2-no-path",
    heading: "Group section 2",
    path: "",
    type: "section-group",
    childrenIds: ["page 2-/course/cou1/page/pag2"],
    parentId: "chapter 1 heading-/course/cou1/chapter/cha1",
  },
  "page 2-/course/cou1/page/pag2": {
    id: "page 2-/course/cou1/page/pag2",
    heading: "page 2",
    path: "/course/cou1/page/pag2",
    type: "page",
    childrenIds: [
      "panel 1 heading-/course/cou1/page/pag2",
      "panel 2 heading-/course/cou1/page/pag2/panel/pan2",
    ],
    parentId: "Group section 2-no-path",
  },
  "panel 1 heading-/course/cou1/page/pag2": {
    id: "panel 1 heading-/course/cou1/page/pag2",
    heading: "panel 1 heading",
    path: "/course/cou1/page/pag2",
    type: "page-panel",
    childrenIds: [],
    parentId: "page 2-/course/cou1/page/pag2",
  },
  "panel 2 heading-/course/cou1/page/pag2/panel/pan2": {
    id: "panel 2 heading-/course/cou1/page/pag2/panel/pan2",
    heading: "panel 2 heading",
    path: "/course/cou1/page/pag2/panel/pan2",
    type: "page-panel",
    childrenIds: [],
    parentId: "page 2-/course/cou1/page/pag2",
  },
  "chapter 2 heading-/course/cou1/chapter/cha2": {
    id: "chapter 2 heading-/course/cou1/chapter/cha2",
    heading: "chapter 2 heading",
    path: "/course/cou1/chapter/cha2",
    type: "chapter",
    index: "2",
    childrenIds: ["Group 2-no-path", "Section 1-c2-no-path"],
    parentId: "cou1",
  },
  "Group 2-no-path": {
    id: "Group 2-no-path",
    heading: "Group with tasks",
    path: "",
    type: "question-group",
    childrenIds: [
      "task /course/cou1/task/tas1",
      "task /course/cou1/task/tas1_1",
      "task /course/cou1/task/tas1_2",
      "task /course/cou1/task/tas1_3",
      "task /course/cou1/task/tas1_4",
    ],
    parentId: "chapter 2 heading-/course/cou1/chapter/cha2",
  },
  "task /course/cou1/task/tas1": {
    id: "task /course/cou1/task/tas1",
    heading: "task page 1",
    path: "/course/cou1/task/tas1",
    type: "page",
    index: "1",
    childrenIds: [],
    parentId: "Group 2-no-path",
  },
  "task /course/cou1/task/tas1_1": {
    id: "task /course/cou1/task/tas1_1",
    heading: "task page 1_1",
    path: "/course/cou1/task/tas1_1",
    type: "page",
    index: "2",
    childrenIds: [],
    parentId: "Group 2-no-path",
  },
  "task /course/cou1/task/tas1_2": {
    id: "task /course/cou1/task/tas1_2",
    heading: "task page 1_2",
    path: "/course/cou1/task/tas1_2",
    type: "page",
    index: "3",
    childrenIds: [],
    parentId: "Group 2-no-path",
  },
  "task /course/cou1/task/tas1_3": {
    id: "task /course/cou1/task/tas1_3",
    heading: "task page 1_3",
    path: "/course/cou1/task/tas1_3",
    type: "page",
    index: "4",
    childrenIds: [],
    parentId: "Group 2-no-path",
  },
  "task /course/cou1/task/tas1_4": {
    id: "task /course/cou1/task/tas1_4",
    heading: "task page 1_4",
    path: "/course/cou1/task/tas1_4",
    type: "page",
    index: "5",
    childrenIds: [],
    parentId: "Group 2-no-path",
  },
  "Section 1-c2-no-path": {
    id: "Section 1-c2-no-path",
    heading: "Group section 1 in Chapter 2",
    type: "section-group",
    childrenIds: [
      "task /course/cou1/task/tas2",
      "page /course/cou1/page/pag3",
      "page /course/cou1/page/pag4",
    ],
    parentId: "chapter 2 heading-/course/cou1/chapter/cha2",
  },
  "task /course/cou1/task/tas2": {
    id: "task /course/cou1/task/tas2",
    heading: "task page 2",
    path: "/course/cou1/task/tas2",
    type: "page",
    childrenIds: [],
    parentId: "Section 1-c2-no-path",
  },
  "page /course/cou1/page/pag3": {
    id: "page /course/cou1/page/pag3",
    heading: "Page 3 chapter 2",
    path: "/course/cou1/page/pag3",
    type: "page",
    childrenIds: [],
    parentId: "Section 1-c2-no-path",
  },
  "page /course/cou1/page/pag4": {
    id: "page /course/cou1/page/pag4",
    heading: "Page 4 chapter 2",
    path: "/course/cou1/page/pag4",
    type: "page",
    childrenIds: [],
    parentId: "Section 1-c2-no-path",
  },
};
